### ISSUE TITLE
General Layout

### ISSUE THREAD

**Issue by curtis-h** [hackference/hackference-2015#13]
Don't like initial blurb:
"Hackference is coming around again and we want to make it as good as it can be for our attendees! And to do that we need your help with the conference and hackathon."
Would replace with "About Hackference" blurb and leave "If you'd like to discuss sponsoring Hackference, please contact sponsorship@hackference.co.uk" to the bottom. 

When doing this also remove "The Basics" heading.

Maybe consider having a "Why Sponsor" section above the packages to tell them what they will be getting out of it.

**Comment by jakeydevs** [comment]
New website should change this.
