### ISSUE TITLE
Smaller Issues

### ISSUE THREAD

**Issue by jakeydevs** [hackference/hackference-2015#16]
- The call to action on the speakers page isn't aligned to picture, and text
- Tim needs a one liner
- Proactive needs a tag line
- Website needs META information
- Conference and Hackathon text needs to be left aligned to fit in with the rest of the site
- Discount code on ti.to needs to be styled
- Footer tag isn't the same as main site tag

**Comment by ukmadlz** [comment]
Can we split these into different issues?

**Comment by jakeydevs** [comment]
Should only take 1 commit to fix all

**Comment by ukmadlz** [comment]
Remaining Items:
Tim needs a one liner
Proactive needs a tag line
Website needs META information
Discount code on ti.to needs to be styled

**Comment by jakeydevs** [comment]
Proactive TAG LINE has been added

**Comment by jakeydevs** [comment]
All changes and made, and deployed
